// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "product-wallet/internal/entity"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "product-wallet/internal/model"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateTx provides a mock function with given fields: ctx, tx, data
func (_m *UserRepository) CreateTx(ctx context.Context, tx *gorm.DB, data *entity.User) error {
	ret := _m.Called(ctx, tx, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.User) error); ok {
		r0 = rf(ctx, tx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByIDTx provides a mock function with given fields: ctx, tx, id
func (_m *UserRepository) DeleteByIDTx(ctx context.Context, tx *gorm.DB, id string) error {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIDTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, tx, order, filter
func (_m *UserRepository) Find(ctx context.Context, tx *gorm.DB, order model.OrderParam, filter model.FilterParams) (*[]entity.User, error) {
	ret := _m.Called(ctx, tx, order, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *[]entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, model.OrderParam, model.FilterParams) (*[]entity.User, error)); ok {
		return rf(ctx, tx, order, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, model.OrderParam, model.FilterParams) *[]entity.User); ok {
		r0 = rf(ctx, tx, order, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, model.OrderParam, model.FilterParams) error); ok {
		r1 = rf(ctx, tx, order, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByColumn provides a mock function with given fields: ctx, tx, filter, order
func (_m *UserRepository) FindByFilter(ctx context.Context, tx *gorm.DB, filter model.FilterParams, order model.OrderParam) (*entity.User, error) {
	ret := _m.Called(ctx, tx, filter, order)

	if len(ret) == 0 {
		panic("no return value specified for FindByFilter")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, model.FilterParams, model.OrderParam) (*entity.User, error)); ok {
		return rf(ctx, tx, filter, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, model.FilterParams, model.OrderParam) *entity.User); ok {
		r0 = rf(ctx, tx, filter, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, model.FilterParams, model.OrderParam) error); ok {
		r1 = rf(ctx, tx, filter, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, tx, id
func (_m *UserRepository) FindByID(ctx context.Context, tx *gorm.DB, id string) (*entity.User, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) (*entity.User, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, string) *entity.User); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, string) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPagination provides a mock function with given fields: ctx, tx, page, order, filter
func (_m *UserRepository) FindByPagination(ctx context.Context, tx *gorm.DB, page model.PaginationParam, order model.OrderParam, filter model.FilterParams) (*model.PaginationData[entity.User], error) {
	ret := _m.Called(ctx, tx, page, order, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindByPagination")
	}

	var r0 *model.PaginationData[entity.User]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, model.PaginationParam, model.OrderParam, model.FilterParams) (*model.PaginationData[entity.User], error)); ok {
		return rf(ctx, tx, page, order, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, model.PaginationParam, model.OrderParam, model.FilterParams) *model.PaginationData[entity.User]); ok {
		r0 = rf(ctx, tx, page, order, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PaginationData[entity.User])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, model.PaginationParam, model.OrderParam, model.FilterParams) error); ok {
		r1 = rf(ctx, tx, page, order, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAssociationMany2ManyTx provides a mock function with given fields: tx, data
func (_m *UserRepository) UpdateAssociationMany2ManyTx(tx *gorm.DB, data *entity.User) error {
	ret := _m.Called(tx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAssociationMany2ManyTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *entity.User) error); ok {
		r0 = rf(tx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTx provides a mock function with given fields: ctx, tx, data
func (_m *UserRepository) UpdateTx(ctx context.Context, tx *gorm.DB, data *entity.User) error {
	ret := _m.Called(ctx, tx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.User) error); ok {
		r0 = rf(ctx, tx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTxWithAssociations provides a mock function with given fields: ctx, tx, data
func (_m *UserRepository) UpdateTxWithAssociations(ctx context.Context, tx *gorm.DB, data *entity.User) error {
	ret := _m.Called(ctx, tx, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTxWithAssociations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.User) error); ok {
		r0 = rf(ctx, tx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
