version: '3.8'
networks:
  service-conn:
    driver: bridge

services:
  product-wallet-web:
    build: .
    command: ["./product-wallet-web"]
    ports:
      - "9004:9004"
    environment:
      APP_NAME: "product-wallet"
      APP_ENV: "development"
      GIN_MODE: "release"
      APP_DEBUG: "true"
      APP_VERSION: "v1"
      HTTP_PORT: "9004"
      JWT_SECRET_ACCESS_TOKEN: "wkhB8NarrReKujasQzlRaOQGOO4S1G884ol9SIyQ7Fr4zxLBJI9Ezml4DeaisAss"
      DB_CONNECTION: "postgres"
      DB_HOST: "postgres-product-wallet"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DATABASE: "product_wallet"
      DB_PREFIX: "product_wallet_"
      ALLOW_ORIGINS: "*"
      ALLOW_METHODS: "POST,GET,PUT,DELETE,OPTIONS"
      ALLOW_HEADERS: "*"
      LOG_PATH: "./logs/"
    restart: on-failure
    networks:
      - service-conn
  postgres-product-wallet:
    image: postgres:14.12
    container_name: postgres-product-wallet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_wallet
    ports:
      - "5432:5432"
    networks:
      - service-conn
